version: '3.9'

services:
  web:
    container_name: iweather
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
        - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  postgres_data: