version: '3.9'

services:
  web:
    container_name: iweather
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_DB=iweather
    ports:
      - "5432:5432"

volumes:
  postgres_data: